<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lanugages = [
            ["id" => 1, "name" => "English", "code" => "en"],
            ["id" => 2, "name" => "Afar", "code" => "aa"],
            ["id" => 3, "name" => "Abkhazian", "code" => "ab"],
            ["id" => 4, "name" => "Afrikaans", "code" => "af"],
            ["id" => 5, "name" => "Amharic", "code" => "am"],
            ["id" => 6, "name" => "Arabic", "code" => "ar"],
            ["id" => 7, "name" => "Assamese", "code" => "as"],
            ["id" => 8, "name" => "Aymara", "code" => "ay"],
            ["id" => 9, "name" => "Azerbaijani", "code" => "az"],
            ["id" => 10, "name" => "Bashkir", "code" => "ba"],
            ["id" => 11, "name" => "Belarusian", "code" => "be"],
            ["id" => 12, "name" => "Bulgarian", "code" => "bg"],
            ["id" => 13, "name" => "Bihari", "code" => "bh"],
            ["id" => 14, "name" => "Bislama", "code" => "bi"],
            ["id" => 15, "name" => "Bengali/Bangla", "code" => "bn"],
            ["id" => 16, "name" => "Tibetan", "code" => "bo"],
            ["id" => 17, "name" => "Breton", "code" => "br"],
            ["id" => 18, "name" => "Catalan", "code" => "ca"],
            ["id" => 19, "name" => "Corsican", "code" => "co"],
            ["id" => 20, "name" => "Czech", "code" => "cs"],
            ["id" => 21, "name" => "Welsh", "code" => "cy"],
            ["id" => 22, "name" => "Danish", "code" => "da"],
            ["id" => 23, "name" => "German", "code" => "de"],
            ["id" => 24, "name" => "Bhutani", "code" => "dz"],
            ["id" => 25, "name" => "Greek", "code" => "el"],
            ["id" => 26, "name" => "Esperanto", "code" => "eo"],
            ["id" => 27, "name" => "Spanish", "code" => "es"],
            ["id" => 28, "name" => "Estonian", "code" => "et"],
            ["id" => 29, "name" => "Basque", "code" => "eu"],
            ["id" => 30, "name" => "Persian", "code" => "fa"],
            ["id" => 31, "name" => "Finnish", "code" => "fi"],
            ["id" => 32, "name" => "Fiji", "code" => "fj"],
            ["id" => 33, "name" => "Faeroese", "code" => "fo"],
            ["id" => 34, "name" => "French", "code" => "fr"],
            ["id" => 35, "name" => "Frisian", "code" => "fy"],
            ["id" => 36, "name" => "Irish", "code" => "ga"],
            ["id" => 37, "name" => "Scots/Gaelic", "code" => "gd"],
            ["id" => 38, "name" => "Galician", "code" => "gl"],
            ["id" => 39, "name" => "Guarani", "code" => "gn"],
            ["id" => 40, "name" => "Gujarati", "code" => "gu"],
            ["id" => 41, "name" => "Hausa", "code" => "ha"],
            ["id" => 42, "name" => "Hindi", "code" => "hi"],
            ["id" => 43, "name" => "Croatian", "code" => "hr"],
            ["id" => 44, "name" => "Hungarian", "code" => "hu"],
            ["id" => 45, "name" => "Armenian", "code" => "hy"],
            ["id" => 46, "name" => "Interlingua", "code" => "ia"],
            ["id" => 47, "name" => "Interlingue", "code" => "ie"],
            ["id" => 48, "name" => "Inupiak", "code" => "ik"],
            ["id" => 49, "name" => "Indonesian", "code" => "in"],
            ["id" => 50, "name" => "Icelandic", "code" => "is"],
            ["id" => 51, "name" => "Italian", "code" => "it"],
            ["id" => 52, "name" => "Hebrew", "code" => "iw"],
            ["id" => 53, "name" => "Japanese", "code" => "ja"],
            ["id" => 54, "name" => "Yiddish", "code" => "ji"],
            ["id" => 55, "name" => "Javanese", "code" => "jw"],
            ["id" => 56, "name" => "Georgian", "code" => "ka"],
            ["id" => 57, "name" => "Kazakh", "code" => "kk"],
            ["id" => 58, "name" => "Greenlandic", "code" => "kl"],
            ["id" => 59, "name" => "Cambodian", "code" => "km"],
            ["id" => 60, "name" => "Kannada", "code" => "kn"],
            ["id" => 61, "name" => "Korean", "code" => "ko"],
            ["id" => 62, "name" => "Kashmiri", "code" => "ks"],
            ["id" => 63, "name" => "Kurdish", "code" => "ku"],
            ["id" => 64, "name" => "Kirghiz", "code" => "ky"],
            ["id" => 65, "name" => "Latin", "code" => "la"],
            ["id" => 66, "name" => "Lingala", "code" => "ln"],
            ["id" => 67, "name" => "Laothian", "code" => "lo"],
            ["id" => 68, "name" => "Lithuanian", "code" => "lt"],
            ["id" => 69, "name" => "Latvian/Lettish", "code" => "lv"],
            ["id" => 70, "name" => "Malagasy", "code" => "mg"],
            ["id" => 71, "name" => "Maori", "code" => "mi"],
            ["id" => 72, "name" => "Macedonian", "code" => "mk"],
            ["id" => 73, "name" => "Malayalam", "code" => "ml"],
            ["id" => 74, "name" => "Mongolian", "code" => "mn"],
            ["id" => 75, "name" => "Moldavian", "code" => "mo"],
            ["id" => 76, "name" => "Marathi", "code" => "mr"],
            ["id" => 77, "name" => "Malay", "code" => "ms"],
            ["id" => 78, "name" => "Maltese", "code" => "mt"],
            ["id" => 79, "name" => "Burmese", "code" => "my"],
            ["id" => 80, "name" => "Nauru", "code" => "na"],
            ["id" => 81, "name" => "Nepali", "code" => "ne"],
            ["id" => 82, "name" => "Dutch", "code" => "nl"],
            ["id" => 83, "name" => "Norwegian", "code" => "no"],
            ["id" => 84, "name" => "Occitan", "code" => "oc"],
            ["id" => 85, "name" => "(Afan)/Oromoor/Oriya", "code" => "om"],
            ["id" => 86, "name" => "Punjabi", "code" => "pa"],
            ["id" => 87, "name" => "Polish", "code" => "pl"],
            ["id" => 88, "name" => "Pashto/Pushto", "code" => "ps"],
            ["id" => 89, "name" => "Portuguese", "code" => "pt"],
            ["id" => 90, "name" => "Quechua", "code" => "qu"],
            ["id" => 91, "name" => "Rhaeto-Romance", "code" => "rm"],
            ["id" => 92, "name" => "Kirundi", "code" => "rn"],
            ["id" => 93, "name" => "Romanian", "code" => "ro"],
            ["id" => 94, "name" => "Russian", "code" => "ru"],
            ["id" => 95, "name" => "Kinyarwanda", "code" => "rw"],
            ["id" => 96, "name" => "Sanskrit", "code" => "sa"],
            ["id" => 97, "name" => "Sindhi", "code" => "sd"],
            ["id" => 98, "name" => "Sangro", "code" => "sg"],
            ["id" => 99, "name" => "Serbo-Croatian", "code" => "sh"],
            ["id" => 100, "name" => "Singhalese", "code" => "si"],
            ["id" => 101, "name" => "Slovak", "code" => "sk"],
            ["id" => 102, "name" => "Slovenian", "code" => "sl"],
            ["id" => 103, "name" => "Samoan", "code" => "sm"],
            ["id" => 104, "name" => "Shona", "code" => "sn"],
            ["id" => 105, "name" => "Somali", "code" => "so"],
            ["id" => 106, "name" => "Albanian", "code" => "sq"],
            ["id" => 107, "name" => "Serbian", "code" => "sr"],
            ["id" => 108, "name" => "Siswati", "code" => "ss"],
            ["id" => 109, "name" => "Sesotho", "code" => "st"],
            ["id" => 110, "name" => "Sundanese", "code" => "su"],
            ["id" => 111, "name" => "Swedish", "code" => "sv"],
            ["id" => 112, "name" => "Swahili", "code" => "sw"],
            ["id" => 113, "name" => "Tamil", "code" => "ta"],
            ["id" => 114, "name" => "Telugu", "code" => "te"],
            ["id" => 115, "name" => "Tajik", "code" => "tg"],
            ["id" => 116, "name" => "Thai", "code" => "th"],
            ["id" => 117, "name" => "Tigrinya", "code" => "ti"],
            ["id" => 118, "name" => "Turkmen", "code" => "tk"],
            ["id" => 119, "name" => "Tagalog", "code" => "tl"],
            ["id" => 120, "name" => "Setswana", "code" => "tn"],
            ["id" => 121, "name" => "Tonga", "code" => "to"],
            ["id" => 122, "name" => "Turkish", "code" => "tr"],
            ["id" => 123, "name" => "Tsonga", "code" => "ts"],
            ["id" => 124, "name" => "Tatar", "code" => "tt"],
            ["id" => 125, "name" => "Twi", "code" => "tw"],
            ["id" => 126, "name" => "Ukrainian", "code" => "uk"],
            ["id" => 127, "name" => "Urdu", "code" => "ur"],
            ["id" => 128, "name" => "Uzbek", "code" => "uz"],
            ["id" => 129, "name" => "Vietnamese", "code" => "vi"],
            ["id" => 130, "name" => "Volapuk", "code" => "vo"],
            ["id" => 131, "name" => "Wolof", "code" => "wo"],
            ["id" => 132, "name" => "Xhosa", "code" => "xh"],
            ["id" => 133, "name" => "Yoruba", "code" => "yo"],
            ["id" => 134, "name" => "Chinese", "code" => "zh"],
            ["id" => 135, "name" => "Zulu", "code" => "zu"],
        ];
        DB::table('languages')->insert($lanugages);
    }
}